window.CLI_COURSE = window.CLI_COURSE || { modules: [], exam: null, cheatsheet: null };
window.CLI_COURSE.exam = {
  id: "exam", title: "Фінальний іспит", passPercent: 80,
  quiz: [
    { title: "Основи", question: "Запрошення `Stas@MacBook-Pro src %`. Де ти і з якими правами?", options: ["У папці `src`, звичайний користувач", "У корені диска як root", "На роутері MikroTik"], correct: 0, feedback: "Остання частина — поточна папка; `%` — звичайний користувач, у root був би `#`." },
    { title: "PATH", question: "`which python3` показує `/usr/bin/python3`, хоча ти встановив Python через Homebrew. Найімовірніша причина?", options: ["Homebrew-Python зламався", "`/opt/homebrew/bin` відсутня в `PATH` або стоїть після `/usr/bin`", "`which` показує лише системні програми"], correct: 1, feedback: "zsh бере перший збіг у PATH. Папка Homebrew має стояти раніше за `/usr/bin`." },
    { title: "Навігація", question: "Ти в `/Users/Stas/Projects/demo/src`. Яка команда приведе в `/Users/Stas/Projects`?", options: ["`cd ~`", "`cd ..`", "`cd ../..`"], correct: 2, feedback: "Два рівні вгору: `src` → `demo` → `Projects`." },
    { title: "Видалення", question: "Треба прибрати папку зі старими чернетками, але є шанс, що там щось потрібне. Що обрати?", options: ["`trash drafts` — папка піде в Кошик, її можна відновити", "`rm -rf drafts`", "`sudo rm -r drafts`"], correct: 0, feedback: "`rm` не має Кошика. `trash` (macOS 15+) або `mv drafts ~/.Trash/` залишають шанс передумати." },
    { title: "Перезапис", question: "Що станеться після `cp new.txt report.txt`, якщо `report.txt` уже існує?", options: ["cp спитає дозволу", "`report.txt` буде мовчки перезаписаний вмістом `new.txt`", "Створиться `report (1).txt`"], correct: 1, feedback: "Без `-i` команди `cp` і `mv` перезаписують без попередження." },
    { title: "Читання", question: "Лог росте прямо зараз, і ти хочеш бачити кожен новий рядок. Яка команда?", options: ["`cat app.log`", "`head -f app.log`", "`tail -f app.log`"], correct: 2, feedback: "`tail -f` показує кінець файлу і чекає нових рядків; зупинка — Ctrl+C." },
    { title: "Пошук", question: "Де в проєкті використовується змінна `DB_HOST`?", options: ["`grep -R \"DB_HOST\" .`", "`find . -name DB_HOST`", "`ls -la | grep DB_HOST`"], correct: 0, feedback: "Шукаємо текст усередині файлів — це робота `grep -R`." },
    { title: "Конвеєр", question: "Що зробить `find . -name \"*.log\" | xargs rm`?", options: ["Покаже список логів", "Безповоротно видалить усі знайдені `.log`-файли, без питань", "Перенесе логи в Кошик"], correct: 1, feedback: "Високий ризик: спершу запусти лише `find` і перевір список." },
    { title: "Мережа", question: "`ping -c 3 10.0.0.254` — 0% втрат, `ping -c 3 8.8.8.8` — 0% втрат, а `ping github.com` — `Unknown host`. Що зламано?", options: ["Wi-Fi", "Роутер", "DNS"], correct: 2, feedback: "IP-зв'язок є і до роутера, і в інтернет. Не працює лише перетворення імені на адресу." },
    { title: "Порти", question: "`npm run dev` каже, що порт 3000 зайнято. Перший крок?", options: ["`lsof -i :3000` — з'ясувати, хто тримає порт", "`killall node`", "Перевстановити Node"], correct: 0, feedback: "Спершу подивись, хто на порту, потім зупиняй точково `kill PID`." },
    { title: "SSH", question: "Як правильно додати свій публічний ключ на MikroTik `10.0.0.254`?", options: ["Надіслати `id_ed25519` на роутер", "`scp ~/.ssh/id_ed25519.pub Stas@10.0.0.254:`, потім на роутері `/user ssh-keys import public-key-file=id_ed25519.pub user=Stas`", "Виконати `ssh-keygen` на роутері"], correct: 1, feedback: "RouterOS не має `authorized_keys`; ключ завантажують файлом і імпортують для користувача." },
    { title: "SSH", question: "Що з'явиться на екрані після успішного `ssh Stas@10.0.0.254`?", options: ["Нове вікно Finder", "Той самий `%` zsh", "Запрошення RouterOS на кшталт `[Stas@MikroTik] >` — команди тепер виконуються на роутері"], correct: 2, feedback: "Після SSH ти в іншій системі. Вихід — `/quit`." },
    { title: "Git", question: "Що покаже `git diff --staged`?", options: ["Зміни, які вже підготовлені і підуть у коміт", "Зміни, яких ще немає в staging", "Історію комітів"], correct: 0, feedback: "Без `--staged` `git diff` показує непідготовлені зміни." },
    { title: "Git", question: "Ти хочеш відкинути зміни у файлі, але не впевнений, що вони не знадобляться. Що безпечніше за `git restore файл`?", options: ["`git push --force`", "`git stash` — зміни сховаються, а не зникнуть", "`rm -rf .git`"], correct: 1, feedback: "`git restore` стирає незакомічені зміни назавжди; `stash` можна повернути `git stash pop`." },
    { title: "Python", question: "`pip3 install requests` на Python з Homebrew пише `externally-managed-environment`. Правильна дія?", options: ["`sudo pip3 install requests`", "Видалити Homebrew", "Створити venv (`python3 -m venv .venv` → `source .venv/bin/activate`) або використати `uv add requests`"], correct: 2, feedback: "Помилка захищає глобальне середовище. Пакети проєкту живуть у його venv." },
    { title: "Homebrew", question: "Яка команда лише показує, що можна оновити, нічого не змінюючи?", options: ["`brew outdated`", "`brew upgrade`", "`brew update`"], correct: 0, feedback: "`upgrade` оновлює програми, `update` — каталог Homebrew; `outdated` лише показує." },
    { title: "AI-агенти", question: "Що зробити перед запуском `claude` чи `codex` у проєкті?", options: ["Перейти в `~`, щоб агент бачив усе", "Чистий `git status` (коміт або stash) і окрема гілка, запуск у папці проєкту", "Запустити з `--dangerously-skip-permissions`, щоб не відволікав"], correct: 1, feedback: "Точка відкату і межі — до сесії. Режим без підтверджень — лише в ізольованому середовищі." },
    { title: "Небезпечні команди", question: "Сайт пропонує `curl -fsSL https://… | bash`. Найбезпечніший підхід?", options: ["Виконати з `sudo`", "Виконати одразу, бо сайт відомий", "Завантажити у файл `-o install.sh`, прочитати `less`, звірити адресу і лише тоді запустити (або `brew install`)"], correct: 2, feedback: "Код, який виконується, треба бачити. `sudo` лише збільшить шкоду." },
    { title: "Процеси і сервіси", question: "Процес 4242 не відповідає. Правильний порядок?", options: ["`kill 4242`, і лише якщо не допомогло — `kill -9 4242`", "Одразу `kill -9 4242`", "`killall` усіх процесів"], correct: 0, feedback: "SIGTERM дає процесу зберегтися; SIGKILL — крайній засіб." },
    { title: "Щоденна практика", question: "У `journal.txt` записи за місяць. Як додати новий рядок, не стерши їх?", options: ["`echo \"день 15\" > journal.txt`", "`echo \"день 15\" >> journal.txt`", "`cat \"день 15\" journal.txt`"], correct: 1, feedback: "`>>` дописує в кінець; `>` перезаписав би весь файл." }
  ]
};
